### ISSUE TITLE
countdown timer componenet

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1097]
count down timer atomic component.

- [x] format is `1d 2h 3m`
- [x] 1 week before ending time start the timer.
- [x] 3 days before ending time timer turns yellow.
- [x] 1 day before ending time timer turns red.
- [ ] before 1 week ending time show ~~`expires`~~  `Reporting Starts` as label with ending time (see breakdown below)
- [x] when current time is past ending time the label turns grey (see mock below)
- [ ] to get start time for next dispute period use the `state.reportingWindowStats.endTime` which is the current fee windows end time.
- [ ] when market is in `open reporting` show label `Open Reporting` no timer or end date.
- [ ] when market endTime, 3 day timer for `Designated Reporting` phase.

![screen shot 2019-02-21 at 11 48 20 am](https://user-images.githubusercontent.com/3970376/53190179-9fad9880-35ce-11e9-8399-5a07abf1cac0.png)

Some things I missed when writing up the tix for John to work for the `My Created Markets` timer that we talked about. 

We need to cover every market reporting status. 
```
  PRE_REPORTING :
-  show label `Reporting begins` With countdown timer
  DESIGNATED_REPORTING:
- we have label ‘Designated Reporting’ and 3 day count down timer from market endTime
  OPEN_REPORTING:
- show label `Open Reporting` since it could be in this state forever. 
  CROWDSOURCING_DISPUTE:
- we show a count down timer until dispute window ends
  AWAITING_NEXT_WINDOW:
- we show a count down timer for the next dispute period
  AWAITING_FINALIZATION:
  FINALIZED:
- these we show `expired` it truly has expired
  FORKING:
- show label `Forking` just for simplicity sake.
  AWAITING_NO_REPORT_MIGRATION:
- show label `Awaiting No Report Migration` for simplicity sake.
  AWAITING_FORK_MIGRATION:
- show label `Awaiting Fork Migration` for simplicity sake
```
