### ISSUE TITLE
Position Display bugs in UI

### ISSUE THREAD

**Issue by nuliknol** [AugurProject/augur#7923]
At order entry, the UI says I am going to make a loss, but this is not true, I am going to make a profit because I am holding the position already. This happens because Augur UI is not aware I am holding the position. 
There is another bug also, that shows "1" in open positions, where in reality I just sold the position and I have 0 positions. The UI should reflect this instantly.

Screenshots attached. Pulled the latest  sources 6 hours ago.
![augur_ui_bug1](https://user-images.githubusercontent.com/1125368/83448615-d56b3f00-a417-11ea-8ad0-2fc131dbd252.png)
![augur_ui_bug2](https://user-images.githubusercontent.com/1125368/83448626-d8fec600-a417-11ea-9a42-cb211f3fe917.png)
![augur_ui_bug3](https://user-images.githubusercontent.com/1125368/83448634-dc924d00-a417-11ea-9721-a158081248b1.png)

**Comment by pgebheim** [comment]
Looking at the screenshot the UI definitely knows about your position (or else the order ticket would not let sell 1@20). The -72.40 is because of the 81.40 in market trading fees that are being incurred on this trade -- there was some work in the last few days on the fees here and we may have messed up the scalar display.

What SHA are you running against?

@bthaile --- Any chance you or chwy tried to fees w/ scalar?

**Comment by pgebheim** [comment]
@nuliknol -- Also what are the details of this market, e.g. the range / numTicks -- from the description looks like the range is (1, 75) ?

**Comment by nuliknol** [comment]
> What SHA are you running against?
> 
the latest commit I am currently running my tests on,  is:
```
commit 4670543b50bef83689c0ab335386666baf7a1137
Merge: 351280cf3d ea3fe411df
Author: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Date:   Mon Jun 1 13:36:36 2020 +0000

```

> Also what are the details of this market, e.g. the range / numTicks -- from the description looks like the range is (1, 75) ?


yes, that is correct, from 1 Million to 75 Million of infected people. 1 unit of tick size
Here is how I am receving the MarketCreated event:

```
MarketCreated event found (block=474)
MarketCreated {
    Universe: 0x82a37C54267b1e9D94C37895Fe26EC232aA55030
    EndTime: 1590408060
    ExtraInfo: {"categories":["Medical","Covid-19",""],"description":"How many people will be infected by COVID 1
9 in Mexico ?","longDescription":"I decide the outcome","_scalarDenomination":"millions","offsetName":null,"templ
ate":null}
    Market: 0xC8e74AD31921C1e271b18E5dfB37148eA526E6aE
    MarketCreator: 0x08434BaC663d786034F2b09cd8F92b5C8168E2d9
    DesignatedReporter: 0x08434BaC663d786034F2b09cd8F92b5C8168E2d9
    FeePerCashInAttoCash: 19900000000000000
    Prices: 1000000000000000000,75000000000000000000
    MarketType: 2
    NumTicks: 74
    Outcomes: 
    NoShowBond: 349680582682291667
    Timestamp: 1590183413
}


```

The UI tries to force you to fractional ticks, but I moved cursor to the left, and erased the dot  along with the chain of zeros
